### ISSUE TITLE
mattermost to support threefold connect

### ISSUE THREAD

**Issue by xmonader** [freeflowuniverse/freeflow_teams_backend#1]
## phase 1

- [x] prepare a fork
- [ ] prepare the build pipeline (build pipelines don't work on forks on github)
- [x] prepare the helm charts
- [x] make sure VDC marketplace works against the forked solutions
- [x] integrate threefold connect (should be a button to loging with threefold connect that starts the auth flow) + callback endpoint that creates the users -how do we deal with different roles?- if these solutions are exposed on the public internet?
- [x] use the current [oauth proxy](https://oauth.threefold.io) 

note: this issue doesn't address anything related to mobile/desktop apps for the solutions, it'd be only usable from the web browser
